tox:
  type: cloud
  target: im-react-native-doc
  dist: docs
  wework:
    ? chatid
  product:
    name: 即时通信IM
    id: CAT010102
  pipelineUrl: http://tencent.coding.woa.com/p/tx/ci/job/678533/build/current
  clashKey: 726c0d9954c76a7962d7e0a8d5f888de
  xingyun:
    department: 通信FT
    service: 云呼叫中心
    app: Web前端
    codereviewer: xingchenhe
